# Generated by Django 4.0.4 on 2022-06-09 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='SKU')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('Precio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio')),
                ('Stock', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stock')),
                ('Descripción', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descripción')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
