# Generated by Django 4.0.4 on 2022-06-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Descripción',
        ),
        migrations.AddField(
            model_name='producto',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción'),
        ),
    ]
